### ISSUE TITLE
Error TypeError: __init__() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by estaji** [sintrb/pytunnel#2]
Hi, I was testing pytunnel and got an error on Python 3.9.2 .
This error showed exactly by using the sample code like this:
on server:
`python -m pytunnel --bind 0.0.0.0:1990`
on client:
`python -m pytunnel --port 1090 --target 127.0.0.1:8080 --server <server_ip>:1990`
and the error is:
`Traceback (most recent call last):
  File "/root/venv/lib/python3.9/site-packages/pytunnel/tunnel.py", line 606, in _run
    ret = self._ready(clt_con, clt_add)
  File "/root/venv/lib/python3.9/site-packages/pytunnel/tunnel.py", line 480, in _ready
    data = json.loads(auth, encoding='utf8')
  File "/usr/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'encoding'`

**Comment by estaji** [comment]
To my way of thinking, this is an error because of new Python versions and changes in json.loads().
There are some useful explanations here: [LINK](https://stackoverflow.com/questions/66032031/why-was-the-keyword-argument-encoding-removed-from-json-loads-in-python-3-9)

**Comment by sintrb** [comment]
I have only tested on Python2.7 and Python3.7. python3.9+ also has process errors. I made some change and simple tests, and now it are working well on 3.9+. Thank you very much for your feedback.
